import type { WorkspaceState } from "@/lib/workspace-model";

export const demoWorkspace: WorkspaceState = {
  version: 1,
  events: [
    {
      id: "event_sabroso_2026",
      name: "Sabroso en San Juan",
      slug: "sabroso-san-juan-2026",
      startsAt: "2026-08-28T23:00:00-03:00",
      venueName: "Hugo Espectáculos",
      city: "San Juan",
      capacity: 500,
      ecosystemMode: "independent",
      websiteStatus: "draft",
      saleStatus: "presale",
      ticketingProvider: "entradaweb",
      externalTicketUrl: "https://www.entradaweb.com.ar/hugo_de_bernardo",
      accredEnabled: false,
      createdAt: "2026-07-29T00:00:00-03:00",
    },
  ],
  campaigns: [
    {
      id: "campaign_sabroso_launch",
      eventId: "event_sabroso_2026",
      name: "Lanzamiento Sabroso 2026",
      objective: "Venta de entradas",
      audience: "Público de cuarteto de 25 a 55 años en San Juan",
      creativeConcept: "Del lado correcto de la noche",
      budgetAmount: null,
      budgetCurrency: "ARS",
      startsAt: "2026-07-30T09:00:00-03:00",
      endsAt: "2026-08-28T23:00:00-03:00",
      status: "planned",
      createdAt: "2026-07-29T00:00:00-03:00",
    },
  ],
  content: [
    {
      id: "content_sabroso_announcement",
      campaignId: "campaign_sabroso_launch",
      title: "Anuncio oficial",
      baseCopy: "Sabroso llega a San Juan. Del lado correcto de la noche.",
      format: "Feed 4:5",
      status: "approved",
      approvedBy: "Hugo",
      approvedAt: "2026-07-29T10:00:00-03:00",
      createdAt: "2026-07-29T09:00:00-03:00",
    },
    {
      id: "content_sabroso_reel",
      campaignId: "campaign_sabroso_launch",
      title: "Reel de clásicos",
      baseCopy: "Una canción. Una historia. Una noche completa de Sabroso.",
      format: "Video 9:16",
      status: "in_review",
      approvedBy: null,
      approvedAt: null,
      createdAt: "2026-07-29T09:30:00-03:00",
    },
    {
      id: "content_sabroso_whatsapp",
      campaignId: "campaign_sabroso_launch",
      title: "Placa WhatsApp",
      baseCopy: "Viernes 28 de agosto, 23 h. Entradas anticipadas disponibles.",
      format: "Estado 9:16",
      status: "draft",
      approvedBy: null,
      approvedAt: null,
      createdAt: "2026-07-29T09:45:00-03:00",
    },
  ],
  publishingTasks: [
    {
      id: "task_sabroso_instagram",
      contentId: "content_sabroso_announcement",
      channel: "instagram",
      scheduledAt: "2026-07-31T20:00:00-03:00",
      status: "scheduled",
      provider: "manual",
    },
    {
      id: "task_sabroso_facebook",
      contentId: "content_sabroso_announcement",
      channel: "facebook",
      scheduledAt: "2026-07-31T20:05:00-03:00",
      status: "scheduled",
      provider: "manual",
    },
    {
      id: "task_sabroso_reel",
      contentId: "content_sabroso_reel",
      channel: "tiktok",
      scheduledAt: "2026-08-04T20:30:00-03:00",
      status: "in_review",
      provider: "manual",
    },
  ],
  activity: [
    {
      id: "activity_seed_1",
      entityType: "event",
      entityId: "event_sabroso_2026",
      action: "event.created",
      summary: "Evento piloto creado en modo independiente.",
      actor: "Sistema demo",
      createdAt: "2026-07-29T00:00:00-03:00",
    },
    {
      id: "activity_seed_2",
      entityType: "content",
      entityId: "content_sabroso_announcement",
      action: "content.approved",
      summary: "Anuncio oficial aprobado para programación manual.",
      actor: "Hugo",
      createdAt: "2026-07-29T10:00:00-03:00",
    },
  ],
};
